### ISSUE TITLE
Map rotation

### ISSUE THREAD

**Issue by mcgratta** [firetools/qgis2fds#27]
I set up a new case today using QGIS2FDS, and everything works great except that when I run the fds case, I see that the FDS domain is rotated about 10 degrees from the QGIS domain. I understand that there is a rotation associated with the Landfire data, but I'm not sure how to ensure that the FDS domain will be the same as the QGIS domain. I did follow the instructions and I believe that I used all the right projections. In QGIS, the rotation angle at the bottom of the screen is zero.

**Comment by emanuelegissi** [comment]
This is a design choice. Let me explain.

In the large majority of the cases the input *digital elevation model*
and *landuse
layer* are aligned to their specific CRS, often with limited local coverage
and in degrees.
To preserve as much as possible the original accuracy of the terrain
description, qgis2fds generates the terrain maintaining the alignment to
the original CRS.

In qgis2fds the FDS MESH is instead always aligned to the unified UTM CRS
<https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system>,
that has several advantages:

   - its coordinates are metric, so perfectly compatible with the FDS
   reference system,
   - it has a worldwide coverage (poles excluded),
   - it has a very broad usage in similar applications.

So the generated terrain geometry is converted to the UTM CRS. It comes out
slightly rotated, *because* it is perfectly aligned to the new CRS.
The resulting FDS y axis points to the geographical north and the
geographical distorsion is reduced to the minimum (much less than 1 m at
our scales).

In brief, we try to have the best of both worlds: the best accuracy for the
terrain, regardless of the esoteric CRS you are using, and a sane default
for the FDS case CRS.
This gives stability to our work: if we had used the original CRSs for
exporting to FDS, instead of the UTM, different CRSs would have created
different GEOMs from the same terrain!

Due to the rotation, qgis2fds creates an FDS MESH line that should always
be enveloped in the terrain, so a little smaller than the qgis2fds "extent".

This is why I always suggest setting a qgis2fds terrain extent that is
120-150% of your FDS domain desired size.
This is useful even if you want to reposition your MESH at a later stage:
you have some margin.

Please, let me know if this is still an issue.

**Comment by emanuelegissi** [comment]
A couple of pictures are better than a thousand words.
Look at what happens when transforming the US map from the NAD83 CRS
EPSG:5070 to the WGS84 CRS EPSG:4326...
[image: US map, CRS is EPSG-5070.png]
[image: US map, CRS is EPSG-4326.png]
This is the reason for the rotation.
The UTM CRS is perfect for small scales (10th of km): low distortion,
metric coordinates

**Comment by mcgratta** [comment]
The images do not appear in my GitHub browser, but I think I understand what you are saying. Is it possible to use the Rotate dialog box in QGIS to rotate the map so that the resulting FDS domain will be consistent with the image in QGIS?

**Comment by mcgratta** [comment]
![Gatlinburg_LS_2_s0000](https://user-images.githubusercontent.com/11333911/96735943-15609d80-138a-11eb-8a16-b3f361916a0a.png)

Why does the FDS domain (black square) not align with the Landfire 30 m patches?

**Comment by emanuelegissi** [comment]
I was not clear enough, sorry. I am sending you the pictures by email,
they are better than any of my explanations.

No, do not rotate the map.
The exported terrain alignment is with the geographical north! Due to the
EPSG:5070 CRS the original landfire data is not north aligned.

**Comment by emanuelegissi** [comment]
I sent you the pictures on your nist.gov email address.
I am adding a new wiki page explaining this, ok?

**Comment by mcgratta** [comment]
OK -- how did you add the wind rose? I could not figure that out.

**Comment by emanuelegissi** [comment]
When in QGIS, click on the menu:
View > Decorations > North Arrow

**Comment by emanuelegissi** [comment]
I leave this open as a reminder for the wiki page.

**Comment by mcgratta** [comment]
The arrow works. Thanks. I was confused because the Quickstart instructions (Step 3) tell us to convert to `WGS84 - EPSG:4326` which shows the map in a typical "north is up" style. My arrow points straight up. I did not realize that the patch of terrain represented by the GEOM line in the FDS input file follows the Landfire patch system, not the normal N-S-E-W system. This is explained in the wiki but I did not read it carefully enough. I do not know how to explain it any differently, so the wiki is OK. Maybe adding the wind rose to the images would be helpful in explaining this. Do you have any idea why the Landfire "patches" are not aligned N-S-E-W?

**Comment by emanuelegissi** [comment]
Disclaimer: I am not an expert, just a user of geographic data. So use this
explanation with caution.

The original problem is that the earth is not flat (believe it or not ;-).
So we use projections to flatten it on a map. Each type of projection has
advantages and disadvantages.

Look at how many different projections we have invented in the last
millennia; of course, each of them is the best for a specific purpose:
https://en.m.wikipedia.org/wiki/List_of_map_projections

Landfire "patches" are not aligned N-S-E-W because they are recorded using
the Conus Albers projection (
https://en.m.wikipedia.org/wiki/Albers_projection) of the EPSG:5070 CRS.

That conical projection is good for data spanning whole continents, as the
US and Canada.

But not good when working at a few tenth of km scale.

In this case UTM is best. It's uses a local cylindrical projection that
flattens the earth in a very smart way, and allows me (and the military,
and rescue teams) to use simple euclidean geometry tools.

And North is always up.

https://en.m.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system

**Comment by mcgratta** [comment]
This is fascinating, Signore Colombo, but it doesn't explain how you ended up in Cuba instead of India ;)

**Comment by emanuelegissi** [comment]
:-)))
