### ISSUE TITLE
How do I find land hight of output topology mesh for vegitation placement

### ISSUE THREAD

**Issue by sterlingbaldwin** [firetools/qgis2fds#39]
Hey, this is a question instead of an issue. Im trying to find a good solution for how to place vegetation on top of the topographic mesh after running qgis2fds. Is there any easy way, given an x/y coordinate, to find the height of the mesh at that point?

**Comment by mcgratta** [comment]
This would be done via the SURF line in the FDS input file. What type of simulation are you doing? What mesh resolution? Level sets? Lagrangian particles?

**Comment by sterlingbaldwin** [comment]
Im doing wildfire modeling, so a fairly course grid over a large domain, and using satellite imagery to identify tree positions. I have the x/y position of the trees/brush, and am using qgis2fds to build the surface mesh from the topographic grid, so I have the rough elevation from the topography file but after qgis2fds builds the mesh I dont know how to find the exact height of the surface mesh for each point I want to place a tree.

**Comment by mcgratta** [comment]
How coarse? If you do not have a grid that is on the order of 1 m resolution, the trees would be irrelevant. It sounds to me that you should be using the level set approach. There is, however, a feature in the latest version of FDS that allows you to populate the terrain with randomly distributed trees. 

Also, are you using the new immersed boundary feature of FDS, the GEOM lines, or are you using the traditional OBST lines. If you are using GEOM, you will probably run into trouble because that feature is experimental at the moment.

**Comment by sterlingbaldwin** [comment]
Im using OBST since the FDS devs recommended away from using GEOM. I havent totally dialed in the grid size yet, but Im shooting for 1m. For the randomly distributed option, can you segment regions of various densities? Do you have any pointers on where I could find more information about the level set approach? The FDS is a hugely complex beast and it seems like there are 5 ways of doing everything, and at least two of them are totally undocumented!

**Comment by mcgratta** [comment]
Have you read the latest version of the FDS User's Guide? If not, read the chapter on wildland fire and then ask specific questions. This is all new material and  under active research.
