### ISSUE TITLE
Headless verification suite is not working locally

### ISSUE THREAD

**Issue by emanuelegissi** [firetools/qgis2fds#77]
I am fixing that, together with much more cleaning to the verifications.

**Comment by johodges** [comment]
Thanks for documenting this. Let me know if you run into issues and want support.

**Comment by emanuelegissi** [comment]
Okay, thank you

**Comment by johodges** [comment]
Local verification is working in ubuntu after merging https://github.com/firetools/qgis2fds/pull/81. Process is to navigate into the verification directory then run "local_verify.sh". This will not work on windows, but should work on macos and linux. @rmcdermo could you test on macos?

**Comment by rmcdermo** [comment]
OK, I will.

**Comment by rmcdermo** [comment]
I may not be up to speed on what I'm supposed to do.  But it did not all work for me.  Here is what I did:

1. I cleaned my repo and checked out the new firetools/dev branch
2. I updated my firemodels/cad repo and opened the qgs file with QGIS

When I try to export the FDS case... a couple things.  First, one macOS all the paths are wrong because this was created on a Windows machine.  Once I fixed those, the export ran, but did not produce an FDS input file.

I have to leave now, but maybe tomorrow we can go over this together and check what I did wrong.

**Comment by johodges** [comment]
Running the verification cases is run from the command line. The process to run should be:
- source <fds installation directory>/bin/FDS6VARS.sh
- source <fds installation directory>/bin/SMV6VARS.sh
- cd <qgis2fds repo directory>/verification
- bash local_verify.sh

I'll plan to join the meeting tomorrow from my linux machine to show the process.

**Comment by emanuelegissi** [comment]
We are reworking the verification suite, see #86 for the relevant discussion.
