### ISSUE TITLE
Incompatible Windows paths, when qgs file is opened in Linux or Mac (FDS case path, csv file paths, ...)

### ISSUE THREAD

**Issue by emanuelegissi** [firetools/qgis2fds#84]
The verification cases are affected, and many more cases.

**Comment by johodges** [comment]
Thanks for the heads up. It's been a while since I have looked at the files embedded in the qgs files. The command line verification suite doesn't use the values embedded in the file since they are overwritten in the command line. I'll take a look at the qgs project files and make sure the embedded values work out the gate as well.

**Comment by emanuelegissi** [comment]
Should be ok, please reopen if not ok
