### ISSUE TITLE
Execution failed. KeyError: 125.0  

### ISSUE THREAD

**Issue by rakyuv** [firetools/qgis2fds#94]
Hi, 
I downloaded a tif file using elevation module of python. I'm interested to export the terrain information in the tif file for FDS using qgis2fds. At the moment, I'm trying to export it as OBST. In the future, I'm interested to export the topography as GEOM.

I'm not able to upload the tif file in here. This is my [error](https://github.com/user-attachments/assets/9fc19633-b99d-4284-851e-8a6f808e11af)

These are my [parameters](https://github.com/user-attachments/assets/4a5f0848-f2b9-4a10-9fd1-71220e715188)

Could you please help me resolve this problem ?

Thanks

**Comment by rakyuv** [comment]
Hi @johodges. Thank you for your answer. This is the input [tif](https://github.com/user-attachments/files/17310045/inputElevation.tif.zip) file that I used

If it the input_elevation.tif doesn't open properly, this is the python script that I used to download the terrain:
```
inputFile = 'inputElevation.tif'

sourceLat = 43.41267431
sourceLon = -0.642749299

left   = sourceLon-0.02
bottom = sourceLat-0.02
right  = sourceLon+0.02
top    = sourceLat+0.02
print('Left, Bottom, Right, Top', left, bottom, right, top)
elevation.clip(bounds=(left, bottom, right, top), output=inputFile)
elevation.clean()
```

**Comment by johodges** [comment]
Thanks for uploading the file. I am traveling today but will try with your
file when I am back in the office.

**Comment by rakyuv** [comment]
Thanks @johodges. I will wait for your answer

**Comment by johodges** [comment]
This issue is already fixed in the development branch. You can find instructions on migrating your plugin installation to develop here:

https://github.com/firetools/qgis2fds/wiki/Install

Here is the project file I am using with develop.

[python_elevation_issue.zip](https://github.com/user-attachments/files/17316841/python_elevation_issue.zip)

Going to close out this issue for now, but feel free to re-open if you still run into issues.
